### ISSUE TITLE
The trianed network does not give out instance segmentation masks. 

### ISSUE THREAD

**Issue by TaiToTo** [dliu5812/PDAM#2]
I tried simulating your experiments on your paper "Unsupervised Instance Segmentation in Microscopy Images via Panoptic Domain
Adaptation and Task Re-weighting" with fluo2tcga setting. 
But that failed. More concretely, the trained model does not give out instance segmentation results. 
Do you have any ideas why?

I first trained prepared 10000 256*256 sized patches either from 100 fluo train images, and 16 tcga train images. 
Next I trained Cycle GAN with default setting, where the I used those in total 20000 patches. And I converted the 10000 fluorescent images to fluo2tcga images. 
Finally, I trained Cyc-PDAM with the 10000 fluo2tcga images and 10000 tcga images with the default setting ing train_gn_pdam.sh in your code.

I checked that the annotations I made in MSCOCO format was right.

**Comment by dliu5812** [comment]
Hi there,

Could you please provide some example results that you mentioned without segmentation results?

**Comment by TaiToTo** [comment]
Hi.
I am sorry for a late reply. 
An example of an inference on test images is as follows. 
What are proper results supposed to look like?

![bi_mask_breast_1](https://user-images.githubusercontent.com/52999158/122842927-4211ee00-d339-11eb-9426-9dfb4a37c52f.png)
![breast_1](https://user-images.githubusercontent.com/52999158/122842928-42aa8480-d339-11eb-923c-996c0f42801a.png)

**Comment by dliu5812** [comment]
Hi,

I have checked my code locally, and it is correct. If you are running 'python fluo2tcga_infer.py', you will get three predictions for each testing image. I put some prediction demos in this link: 

https://drive.google.com/file/d/1gfP_zMcPkLt2HJdRJldxN760yd4Mfk4K/view?usp=sharing

For the instance segmentation results, you should refer to the predictions named 'xxx.tif'. For the prediction overlapped with the original images, I did not visualize the mask using the inference code in my experiments since the original visualization process in the maskrcnn-benchmark has some bugs. I skip them and write another code to visualize the instance segmentation results. These code will be then uploaded.

**Comment by TaiToTo** [comment]
Thank you very much. 

I trained Cycle GAN with 10000 patches from fluo data and 10000 patches from tcga data. 
Was that right?

And I would appreciate it if you could share the exact command you used on command line to execute Cycle GAN in fluo2tcga setting. 
I am not sure if I could simulate the Cycle GAN part of your experiments.

**Comment by dliu5812** [comment]
Hi,

Yeah, the data split is correct. 

The detailed command line I used to train CycleGAN:

```

python train.py --dataroot ./datasets/your_dataset --name nuclei_cyclegan_fluo2tcga \
--model cycle_gan --pool_size 50 --no_dropout --checkpoints_dir './checkpoints-fluo2tcga' \
--niter 10 --niter_decay 10 --lr_decay_iters 5 --lr 0.0001 --gpu_ids 0 --display_env 'main' --display_freq 50

```

All the variables' names in this command line are the same as the original cyclegan repository (https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).
